### ISSUE TITLE
Request to delete profiles

### ISSUE THREAD

**Issue by fossfreedom** [serdarsen/budgie-browser-profile-launcher#3]
Similar to the creation  issue raised earlier  is it possible to delete a profile from the dropdown. I.e. a trash or x type button would when clicked popup a message dialog to confirm before deleting.

This request is to improve the usability so that users don't need to figure out the command line equivalent action.

**Comment by serdarsen** [comment]
Thanks for your all advice.
Added
* Delete profile option
