### ISSUE TITLE
Suggestion to enable discovery

### ISSUE THREAD

**Issue by fossfreedom** [serdarsen/budgie-browser-profile-launcher#5]
To see the various options per browser you have to click on the Chromium/Chrome option to reveal.

Think it would be much better to right justify the two icons that would be normally in the reveal so that the options are one click away - and much more discoverable.

To see the various options per "Person"  you have to right click - not at all obvious.  Again I would similarly just put the icons right margin justified against each person so it is easier to discover

**Comment by serdarsen** [comment]
Thanks for the suggestion. But i would like to keep the interface like this.

**Comment by fossfreedom** [comment]
Sure. That is entirely up to you 😀

My key focus is the second per profile option. It is not obvious in anyway that there is a right click option.

How about a > button at the beginning or right justified at the end of the browser and profile lines. Clicking the button sends a click or right click event to the line as appropriate to activate the functionality? 

In that way nothing major codewise needs to change.

**Comment by serdarsen** [comment]
:sweat_smile: :smiley: . You were right.

I tried putting drop-down buttons right justified at the end of the lines. Then I thought it was very complicated for users. And it did not look good.

Finally i applied your first suggestion. I think it is more practical and looks nice now.

**Comment by fossfreedom** [comment]
Absolutely superb!  If you don't mind I will package and make this available for all Ubuntu Budgie 18.04 users asap

**Comment by serdarsen** [comment]
Of course. I will be glad.
