### ISSUE TITLE
No option to use any Chromium browser but Chrome

### ISSUE THREAD

**Issue by AlexVDem** [serdarsen/budgie-browser-profile-launcher#7]
Budgie 20.04
No option to use any Chromium browser but Chrome. I have Chromium, Chrome and Brave.
I wish to use budgie-browser-profile-launcher with Brave, but I see only one Chrome profiles, no other browsers. Brave is my default browser in settings.
"+" in profile launcher just start Chrome Browser.
Thanks.

**Comment by serdarsen** [comment]
This Applet Moved Under The [UbuntuBudgie / budgie-browser-profile-launcher](https://github.com/UbuntuBudgie/budgie-browser-profile-launcher)
